services:
    sge_web:
        build: .
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - sge_db
        env_file:
            - .env

    sge_db:
        image: postgres:15
        ports:
            - 5434:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env

volumes:
    postgres_data:

